"use client";

import { PointerEvent } from "react";
import type { CustomLayout, Template, TemplateTypography } from "./types";

type Props = { template: Template; layout: CustomLayout; typography: TemplateTypography; name: string; course: string; date: string; index: number; onLayoutChange: (event: PointerEvent<HTMLElement>) => void; onDragStart: (element: "box" | "name", event: PointerEvent<HTMLElement>) => void; onDragEnd: () => void };

export default function DraggableTemplatePreview({ template, layout, typography, name, course, date, index, onLayoutChange, onDragStart, onDragEnd }: Props) {
  const colors = template.colors ?? { background: "#ffffff", accent: "#145c4a", text: "#172521" };
  const textStyle = { "--label-size": `${typography.label}cqh`, "--name-size": `${typography.name}cqh`, "--body-size": `${typography.body}cqh`, "--meta-size": `${typography.meta}cqh` } as React.CSSProperties;
  return <div className="preview-column"><div className={`certificate-preview preview-${index % 3} ${template.background ? "uploaded-preview" : ""}`} onPointerMove={onLayoutChange} onPointerUp={onDragEnd} onPointerCancel={onDragEnd}>{template.background ? <><div className="uploaded-art" style={{ backgroundImage: `url("${template.background}")` }} /><div className="uploaded-details" style={{ left: `${layout.box.x}%`, top: `${layout.box.y}%` }} onPointerDown={(event) => { onDragStart("box", event); event.stopPropagation(); }} /><div className="uploaded-content-group" style={{ ...textStyle, left: `${layout.name.x}%`, top: `${layout.name.y}%`, color: colors.text }} onPointerDown={(event) => { onDragStart("name", event); event.stopPropagation(); }}><small>Awarded to</small><strong style={{ color: colors.accent }}>{name || "Recipient name"}</strong><em>has successfully completed</em><span>{course || "Course or achievement"} · {date}</span><code>Verification ID will appear on the certificate</code></div></> : <div className="preview-border" style={{ background: colors.background, borderColor: colors.accent, color: colors.text }}><div className="seal" style={{ background: colors.accent }}>✦</div><p className="preview-kicker" style={{ color: colors.accent }}>CERTIFICATE OF ACHIEVEMENT</p><h2>{name || "Recipient name"}</h2><p>has successfully completed</p><strong style={{ color: colors.accent }}>{course || "Course or achievement"}</strong><small>Issued {date || "YYYY-MM-DD"}</small></div>}</div><p className="preview-caption">{template.background ? "Drag the complete text block to position it" : `Live preview · ${template.name}`}</p></div>;
}
